FROM maven:3.5.2-jdk-8-alpine
LABEL authors=PrivaliaQATeam

#============================================
# Networking tools
#============================================
RUN apk add --no-cache vim iputils openssh-client
